coverage:
  status:
    project:
      default:
        target: auto
        threshold: 80% 

flags:
  unit-tests:
    paths:
      - src/FIAP_CloudGames.Domain/

fixes:
  - "::/home/runner/work/Fiap-Cloud-Games/Fiap-Cloud-Games/"