coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10% 
        paths: 
          - src/FIAP_CloudGames.Domain/
          - src/FIAP_CloudGames.Application/

fixes:
  - "::/home/runner/work/Fiap-Cloud-Games/Fiap-Cloud-Games/"